name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        coverage run --source danker -m pytest test/
        coveralls
        shellcheck *.sh */*.sh
        python3 -m danker test/graphs/bar-20190301.links 0.85 10 1 -p 5 -i > /dev/null
        ./danker.sh ch
        ./danker.sh sk --project wikisource
        ./danker.sh cv --project wikibooks
        ./danker.sh th --project wikinews
        ./danker.sh hi --project wikiversity
        ./danker.sh uz --project wikiquote
        ./danker.sh ast --project wiktionary
